Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Cml.DataModels;
using Cml.Infrastructure.Managers;
using Cml.Infrastructure.Startup;
using Cml.Transfer;
using Cml.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Services;

namespace Web.Controllers
{
    public class LoginController : CustomBaseController
    {
        private readonly IEndUserManager _userLogicManager_;

        public LoginController(
            IEndUserManager userLogicManager,
            ControllerHelper controllerHelper,
            IAppSettings appSettings,
            ILogger logger
            ) : base(controllerHelper, appSettings, logger)
        {
            _userLogicManager_ = userLogicManager;
        }

        [AllowAnonymous]
        public async Task<ActionResult<Content<EndUser>>> LogIn([FromBody]UserLoginData userLogin)
        {
            var content = await _userLogicManager_.AuthenticateUserAsync(userLogin.Email, userLogin.Password);
            if (!content.HasError)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, content.Data.Name),
                    new Claim(ClaimTypesExt.LastName, content.Data.LastName),
                    new Claim(ClaimTypes.Role, content.Data.Role),
                    new Claim(ClaimTypesExt.Id, content.Data.Id.ToString()),
                };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = false,

                    //todo move to config
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(_appSettings_.CookieExpirePeriodInMins),

                    IsPersistent = true
                };

                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);
            }

            return content;
        }

        [Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        public async Task LogOut()
        {
            await HttpContext.SignOutAsync();
        }

        public async Task CreateAdmin()
        {
            await CreateAdminUser();
        }

        public IActionResult Index()
        {
            var res = GetViewModelOrRedirect(HttpContext);
            return View();
        }

        private async Task CreateAdminUser()
        {
            await _userLogicManager_.AddEntityAsync(
                new EndUser()
                {
                    Email = "admin@mail.com",
                    EmailConfirmed = true,
                    Name = "Mr.",
                    LastName = "Admin",
                    Password = "Admin1234",
                    Role = "admin"
                });
        }
    }
}

Web/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Http;
using Cml.DataModels;
using Cml.Infrastructure.Startup;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Services;

namespace Web.Controllers
{
    public class TestController : CustomBaseController
    {
        public TestController(
            ControllerHelper controllerHelper,
            IAppSettings appSettings,
            ILogger logger
            ) : base(controllerHelper, appSettings, logger) { }

        [System.Web.Http.HttpGet]
        public ActionResult<Int32> Testing()
        {
            return 5;
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        [Microsoft.AspNetCore.Mvc.Route("Test/AuthorizedEndpoint")]
        public ActionResult<String> AuthorizedEndpoint([FromUri]String value)
        {
            return $"AUTHORIZED: Returning value {value}";
        }

        public ActionResult<String> UnuthorizedEndpoint([FromUri]String value)
        {
            var user = HttpContext.User;
            return $"UNAUTHORIZED: Returning value {value}";
        }

        public async Task<ActionResult<String>> Test1([FromUri]String value)
        {
            if (!String.IsNullOrWhiteSpace(value)) return value;
            else return "No value";

        }

        public async Task<ActionResult<String>> SetAdminRole([FromUri]String value)
        {
            if (!String.IsNullOrWhiteSpace(value)) return value;
            try
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Role, Role.ADMIN)
                };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,

                    //todo move to config
                    //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),

                    IsPersistent = true
                };

                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);

                var user = HttpContext.User;
                return "success";
            }
            catch (Exception e)
            {
                return "fail." + e.Message;
            }
        }
        public IActionResult Index()
        {
            return GetViewModelOrRedirect(HttpContext);
        }

    }
}

Web/Controllers/UserController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using Cml.DataModels;
using Cml.Infrastructure.Managers;
using Cml.Infrastructure.Startup;
using Cml.Transfer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Services;
using FromBodyAttribute = Microsoft.AspNetCore.Mvc.FromBodyAttribute;

namespace Web.Controllers
{
    public class UserController : CustomBaseController
    {
        private readonly IEndUserManager _endUserManager_;
        public UserController(
            IEndUserManager endUserManager,
            ControllerHelper controllerHelper,
            IAppSettings appSettings,
            ILogger logger
            ) : base(controllerHelper, appSettings, logger)
        {
            _endUserManager_ = endUserManager;
        }

        [Authorize(Roles = Role.Access.MUST_BE_ADMIN)]
        public async Task<ActionResult<Content<EndUser>>> GetUserById([FromUri]Int32 id)
        {
            return await _endUserManager_.GetEntityAsync(id);
        }

        [Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        public async Task<ActionResult<Content<EndUser>>> Me()
        {
            var result = new Content<EndUser>();
            var idString = HttpContext.User.Claims.FirstOrDefault(x => x.Type.Equals(ClaimTypesExt.Id))?.Value;
            if (!String.IsNullOrWhiteSpace(idString) && Int32.TryParse(idString, out Int32 id))
                result = await _endUserManager_.GetEntityAsync(id);
            else
                result.AppendError(new ArgumentNullException(), "Id not found");

            return result;
        }

        [AllowAnonymous]
        public async Task<ActionResult<Content<Boolean>>> RegisterSelf([FromBody]EndUser user)
        {
            user.Id = 0;
            var result = await _endUserManager_.AddEntityAsync(user);
            return result;
        }

        [Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        public async Task<ActionResult<Content<Boolean>>> UpdateUser([FromBody]EndUser user)
        {
            var resultContent = new Content<Boolean>();
            var idString = HttpContext.User.Claims.FirstOrDefault(x => x.Type.Equals(ClaimTypesExt.Id))?.Value;
            if (!String.IsNullOrWhiteSpace(idString) && Int32.TryParse(idString, out Int32 id))
            {
                user.Id = id;
                var result = await _endUserManager_.UpdateEntityAsync(user);
                if (result.HasError) resultContent.AppendError(result);
                else resultContent.SetData(result.Data);
            }
            else
            {
                resultContent.AppendError(new ArgumentException(), "User not signed in properly.");
            }
            return resultContent;
        }

        [Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        public async Task<ActionResult<Content<Boolean>>> UpdateUserEmail([FromBody]EndUser user)
        {
            var resultContent = new Content<Boolean>();
            var idString = HttpContext.User.Claims.FirstOrDefault(x => x.Type.Equals(ClaimTypesExt.Id))?.Value;
            if (!String.IsNullOrWhiteSpace(idString) && Int32.TryParse(idString, out Int32 id))
            {
                var result = await _endUserManager_.UpdateUserEmailAsync(id, user.Email);
                if (result.HasError) resultContent.AppendError(result);
                else resultContent.SetData(result.Data);
            }
            else
            {
                resultContent.AppendError(new ArgumentException(), "User not signed in properly.");
            }
            return resultContent;
        }

        [Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        public async Task<ActionResult<Content<Boolean>>> UpdateUserPassword([FromBody]EndUser user)
        {
            var resultContent = new Content<Boolean>();
            var idString = HttpContext.User.Claims.FirstOrDefault(x => x.Type.Equals(ClaimTypesExt.Id))?.Value;
            if (!String.IsNullOrWhiteSpace(idString) && Int32.TryParse(idString, out Int32 id))
            {
                var result = await _endUserManager_.UpdateUserPasswordAsync(id, user.Password);
                if (result.HasError) resultContent.AppendError(result);
                else resultContent.SetData(result.Data);
            }
            else
            {
                resultContent.AppendError(new ArgumentException(), "User not signed in properly.");
            }
            return resultContent;
        }

        [Authorize(Roles = Role.Access.MUST_BE_AUTHENTICATED)]
        public IActionResult Index()
        {
            return GetViewModelOrRedirect(HttpContext);
        }

        [AllowAnonymous]
        public IActionResult Register()
        {
            return GetViewModelOrRedirect(HttpContext);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
@model Cml.ViewModels.BaseViewModel

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC5</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MVC5</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="Index">Test</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
                </ul>
            </div>
            <div>
                @{ if (Model != null)
                    {
                        if (Model.User != null && Model.User.Id > 0)
                        {
                            <div>
                                <a asp-area="" asp-controller="User" asp-action="Index">
                                    <div class="text-info">
                                        | @Model.User.Name @Model.User.LastName |
                                    </div>
                                </a>
                                <br />
                                <button id="button-logout">Logout</button>
                            </div>
                        }
                    }
                }
            </div>
        </div>
    </nav>


    <div class="container-fluid body-content">
        <div id="app">
            <template>
                <notifications></notifications>
            </template>
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2021 - MVC5</p>
        </footer>
    </div>
    <partial name="_CookieConsentPartial" />


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        @*---comment out for online libs---*@
        <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@7/dist/polyfill.min.js"></script>

        @*---comment out for offline libs---*@
        @*<script src="~/lib/vue/vue.js"></script>*@
        @*<script src="~/lib/polyfill/polyfill.min.js"></script>*@

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>

        @*---comment out for online libs---*@
        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>

        @*---comment out for offline libs---*@
        @*<script src="~/lib/vue/vue.min.js"></script>*@
        @*<script src="~/lib/polyfill/polyfill.min.js"></script>*@


        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>